version: '3'

services:
  hashgarddnode0:
    container_name: hashgarddnode0
    image: "tendermint/hashgarddnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-hashgardd.log}
    volumes:
      - ./build:/hashgardd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  hashgarddnode1:
    container_name: hashgarddnode1
    image: "tendermint/hashgarddnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-hashgardd.log}
    volumes:
      - ./build:/hashgardd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  hashgarddnode2:
    container_name: hashgarddnode2
    image: "tendermint/hashgarddnode"
    environment:
      - ID=2
      - LOG=${LOG:-hashgardd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/hashgardd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  hashgarddnode3:
    container_name: hashgarddnode3
    image: "tendermint/hashgarddnode"
    environment:
      - ID=3
      - LOG=${LOG:-hashgardd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/hashgardd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

